# Generated by Django 5.0.12 on 2025-02-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Chấp nhận', 'Chấp nhận'), ('Đang chuẩn bị', 'Đang chuẩn bị'), ('Đang Ship', 'Đang Ship'), ('Hoàn Thành', 'Hoàn Thành'), ('Đã hủy', 'Đã hủy')], default='Mới', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Chấp Nhận', 'Chấp Nhận'), ('Đã hủy', 'Đã hủy')], default='Mới', max_length=10),
        ),
    ]
